name: 'docker-compose ssh deploy'
description: 'Deploy a pre-rendered docker-compose.yml via ssh'
inputs:
  ssh_username:  # id of input
    description: 'SSH Username'
    required: true
    default: 'root'
  ssh_host:
    description: 'SSH Host'
    required: true
    default: ''
  ssh_port:
    description: 'SSH Port'
    required: true
    default: '22'
  ssh_key:
    description: 'SSH Key'
    required: true
    default: ''
  project_name:
    description: 'Project Name'
    required: true
    default: ''
  environment:
    description: 'Deploy Enviornment'
    required: true
    default: ''
  docker_registry:
    description: 'Deploy Enviornment'
    required: true
    default: 'https://docker.pkg.github.com'
  docker_registry_user:
    description: 'Deploy Enviornment'
    required: true
    default: ''
  docker_registry_password:
    description: 'Deploy Enviornment'
    required: true
    default: ''
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.ssh_username }} ${{ inputs.ssh_host }} ${{ inputs.ssh_port }} ${{ inputs.ssh_key }} ${{ inputs.project_name }} ${{ inputs.environment }} ${{ inputs.docker_registry }} ${{ inputs.docker_registry_user }} ${{ inputs.docker_registry_password }}
